
package br.ubs.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnidadeSaudeImplService", targetNamespace = "http://soap.ubs.br/", wsdlLocation = "http://10.100.86.163:8080/ubs?wsdl")
public class UnidadeSaudeImplService
    extends Service
{

    private final static URL UNIDADESAUDEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIDADESAUDEIMPLSERVICE_EXCEPTION;
    private final static QName UNIDADESAUDEIMPLSERVICE_QNAME = new QName("http://soap.ubs.br/", "UnidadeSaudeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.86.163:8080/ubs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIDADESAUDEIMPLSERVICE_WSDL_LOCATION = url;
        UNIDADESAUDEIMPLSERVICE_EXCEPTION = e;
    }

    public UnidadeSaudeImplService() {
        super(__getWsdlLocation(), UNIDADESAUDEIMPLSERVICE_QNAME);
    }

    public UnidadeSaudeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIDADESAUDEIMPLSERVICE_QNAME, features);
    }

    public UnidadeSaudeImplService(URL wsdlLocation) {
        super(wsdlLocation, UNIDADESAUDEIMPLSERVICE_QNAME);
    }

    public UnidadeSaudeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIDADESAUDEIMPLSERVICE_QNAME, features);
    }

    public UnidadeSaudeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnidadeSaudeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUnidadeSaudeService
     */
    @WebEndpoint(name = "UnidadeSaudeImplPort")
    public IUnidadeSaudeService getUnidadeSaudeImplPort() {
        return super.getPort(new QName("http://soap.ubs.br/", "UnidadeSaudeImplPort"), IUnidadeSaudeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUnidadeSaudeService
     */
    @WebEndpoint(name = "UnidadeSaudeImplPort")
    public IUnidadeSaudeService getUnidadeSaudeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.ubs.br/", "UnidadeSaudeImplPort"), IUnidadeSaudeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIDADESAUDEIMPLSERVICE_EXCEPTION!= null) {
            throw UNIDADESAUDEIMPLSERVICE_EXCEPTION;
        }
        return UNIDADESAUDEIMPLSERVICE_WSDL_LOCATION;
    }

}
