
package br.cbo.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CboService", targetNamespace = "http://cbo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CboService {


    /**
     * 
     * @return
     *     returns java.util.List<br.cbo.soap.Cbo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListCbo", targetNamespace = "http://cbo/", className = "br.cbo.soap.GetListCbo")
    @ResponseWrapper(localName = "getListCboResponse", targetNamespace = "http://cbo/", className = "br.cbo.soap.GetListCboResponse")
    @Action(input = "http://cbo/CboService/getListCboRequest", output = "http://cbo/CboService/getListCboResponse")
    public List<Cbo> getListCbo();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.cbo.soap.Cbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCbo", targetNamespace = "http://cbo/", className = "br.cbo.soap.GetCbo")
    @ResponseWrapper(localName = "getCboResponse", targetNamespace = "http://cbo/", className = "br.cbo.soap.GetCboResponse")
    @Action(input = "http://cbo/CboService/getCboRequest", output = "http://cbo/CboService/getCboResponse")
    public Cbo getCbo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCbo", targetNamespace = "http://cbo/", className = "br.cbo.soap.SetCbo")
    @ResponseWrapper(localName = "setCboResponse", targetNamespace = "http://cbo/", className = "br.cbo.soap.SetCboResponse")
    @Action(input = "http://cbo/CboService/setCboRequest", output = "http://cbo/CboService/setCboResponse")
    public void setCbo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.cbo.soap.Cbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCbo", targetNamespace = "http://cbo/", className = "br.cbo.soap.RemoveCbo")
    @ResponseWrapper(localName = "removeCboResponse", targetNamespace = "http://cbo/", className = "br.cbo.soap.RemoveCboResponse")
    @Action(input = "http://cbo/CboService/removeCboRequest", output = "http://cbo/CboService/removeCboResponse")
    public Cbo removeCbo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
