
package br.cidade.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CidadeServiceImpService", targetNamespace = "http://soap/", wsdlLocation = "http://10.100.36.65:8080/cidades?wsdl")
public class CidadeServiceImpService
    extends Service
{

    private final static URL CIDADESERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CIDADESERVICEIMPSERVICE_EXCEPTION;
    private final static QName CIDADESERVICEIMPSERVICE_QNAME = new QName("http://soap/", "CidadeServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.36.65:8080/cidades?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CIDADESERVICEIMPSERVICE_WSDL_LOCATION = url;
        CIDADESERVICEIMPSERVICE_EXCEPTION = e;
    }

    public CidadeServiceImpService() {
        super(__getWsdlLocation(), CIDADESERVICEIMPSERVICE_QNAME);
    }

    public CidadeServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CIDADESERVICEIMPSERVICE_QNAME, features);
    }

    public CidadeServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, CIDADESERVICEIMPSERVICE_QNAME);
    }

    public CidadeServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CIDADESERVICEIMPSERVICE_QNAME, features);
    }

    public CidadeServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CidadeServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CidadeService
     */
    @WebEndpoint(name = "CidadeServiceImpPort")
    public CidadeService getCidadeServiceImpPort() {
        return super.getPort(new QName("http://soap/", "CidadeServiceImpPort"), CidadeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CidadeService
     */
    @WebEndpoint(name = "CidadeServiceImpPort")
    public CidadeService getCidadeServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "CidadeServiceImpPort"), CidadeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CIDADESERVICEIMPSERVICE_EXCEPTION!= null) {
            throw CIDADESERVICEIMPSERVICE_EXCEPTION;
        }
        return CIDADESERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
