
package br.fuso.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FusoHorarioImplService", targetNamespace = "http://soap/", wsdlLocation = "http://10.100.34.240:8080/fusohorario?wsdl")
public class FusoHorarioImplService
    extends Service
{

    private final static URL FUSOHORARIOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUSOHORARIOIMPLSERVICE_EXCEPTION;
    private final static QName FUSOHORARIOIMPLSERVICE_QNAME = new QName("http://soap/", "FusoHorarioImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.100.34.240:8080/fusohorario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUSOHORARIOIMPLSERVICE_WSDL_LOCATION = url;
        FUSOHORARIOIMPLSERVICE_EXCEPTION = e;
    }

    public FusoHorarioImplService() {
        super(__getWsdlLocation(), FUSOHORARIOIMPLSERVICE_QNAME);
    }

    public FusoHorarioImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUSOHORARIOIMPLSERVICE_QNAME, features);
    }

    public FusoHorarioImplService(URL wsdlLocation) {
        super(wsdlLocation, FUSOHORARIOIMPLSERVICE_QNAME);
    }

    public FusoHorarioImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUSOHORARIOIMPLSERVICE_QNAME, features);
    }

    public FusoHorarioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FusoHorarioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FusoHorarioService
     */
    @WebEndpoint(name = "FusoHorarioImplPort")
    public FusoHorarioService getFusoHorarioImplPort() {
        return super.getPort(new QName("http://soap/", "FusoHorarioImplPort"), FusoHorarioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FusoHorarioService
     */
    @WebEndpoint(name = "FusoHorarioImplPort")
    public FusoHorarioService getFusoHorarioImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "FusoHorarioImplPort"), FusoHorarioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUSOHORARIOIMPLSERVICE_EXCEPTION!= null) {
            throw FUSOHORARIOIMPLSERVICE_EXCEPTION;
        }
        return FUSOHORARIOIMPLSERVICE_WSDL_LOCATION;
    }

}
