
package br.fuso.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FusoHorarioService", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FusoHorarioService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFusoByCNES", targetNamespace = "http://soap/", className = "br.fuso.soap.RemoveFusoByCNES")
    @ResponseWrapper(localName = "removeFusoByCNESResponse", targetNamespace = "http://soap/", className = "br.fuso.soap.RemoveFusoByCNESResponse")
    @Action(input = "http://soap/FusoHorarioService/removeFusoByCNESRequest", output = "http://soap/FusoHorarioService/removeFusoByCNESResponse")
    public boolean removeFusoByCNES(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFuso", targetNamespace = "http://soap/", className = "br.fuso.soap.AddFuso")
    @ResponseWrapper(localName = "addFusoResponse", targetNamespace = "http://soap/", className = "br.fuso.soap.AddFusoResponse")
    @Action(input = "http://soap/FusoHorarioService/addFusoRequest", output = "http://soap/FusoHorarioService/addFusoResponse")
    public boolean addFuso(
        @WebParam(name = "arg0", targetNamespace = "")
        FusoHorario arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.fuso.soap.FusoHorario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByCNES", targetNamespace = "http://soap/", className = "br.fuso.soap.GetByCNES")
    @ResponseWrapper(localName = "getByCNESResponse", targetNamespace = "http://soap/", className = "br.fuso.soap.GetByCNESResponse")
    @Action(input = "http://soap/FusoHorarioService/getByCNESRequest", output = "http://soap/FusoHorarioService/getByCNESResponse")
    public FusoHorario getByCNES(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.fuso.soap.FusoHorario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://soap/", className = "br.fuso.soap.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://soap/", className = "br.fuso.soap.GetAllResponse")
    @Action(input = "http://soap/FusoHorarioService/getAllRequest", output = "http://soap/FusoHorarioService/getAllResponse")
    public List<FusoHorario> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateFuso", targetNamespace = "http://soap/", className = "br.fuso.soap.UpdateFuso")
    @ResponseWrapper(localName = "updateFusoResponse", targetNamespace = "http://soap/", className = "br.fuso.soap.UpdateFusoResponse")
    @Action(input = "http://soap/FusoHorarioService/updateFusoRequest", output = "http://soap/FusoHorarioService/updateFusoResponse")
    public boolean updateFuso(
        @WebParam(name = "arg0", targetNamespace = "")
        FusoHorario arg0);

}
